swagger: '2.0'
info:
  version: '1.0'
  title: 'giveandtake-backend'
  description: 'Give & Take - Backend'
host: 'api-devl.give-and-take.tk:5000'
schemes: 
  - 'http'
paths:
  /:
    get:
      summary: 'Health check'
      description: 'Test health'
      responses:
        200:
          description: OK
      x-amazon-apigateway-integration:
        type: http
        httpMethod: GET
        uri: http://${stageVariables.env}.give-and-take.tk:5000/
        responses:
          default:
            statusCode: '200'
  /ip:
    get:
      summary: 'IP'
      description: 'Get internal ip of the server machine.'
      responses:
        200:
          description: OK
      x-amazon-apigateway-integration:
        type: http
        httpMethod: GET
        uri: http://${stageVariables.env}.give-and-take.tk:5000/ip
        responses:
          default:
            statusCode: '200'
