swagger: '2.0'
info:
  version: '1.0'
  title: 'giveandtake-backend-${env}'
  description: 'Give & Take - Backend'
host: 'internalapi-devl.give-and-take.tk'
schemes: 
  - 'http'
paths:
  /:
    get:
      summary: 'Health check'
      description: 'Test health'
      responses:
        200:
          description: OK
      x-amazon-apigateway-integration:
        type: http
        httpMethod: GET
        uri: http://${domain}:${port}/
        responses:
          default:
            statusCode: '200'
  /version:
    get:
      summary: 'Check version'
      description: 'Check version'
      responses:
        200:
          description: OK
      x-amazon-apigateway-integration:
        type: http
        httpMethod: GET
        uri: http://${domain}:${port}/version
        responses:
          default:
            statusCode: '200'
  /ip:
    get:
      summary: 'IP'
      description: 'Get internal ip of the server machine.'
      responses:
        200:
          description: OK
      x-amazon-apigateway-integration:
        type: http
        httpMethod: GET
        uri: http://${domain}:${port}/ip
        responses:
          default:
            statusCode: '200'
