swagger: '2.0'
info:
  version: '1.0'
  title: 'giveandtake-backend'
  description: 'Give & Take - Backend'
host: 'api-devl.give-and-take.tk:8080'
schemes: 
  - 'http'
paths:
  /:
    get:
      summary: 'Health check'
      description: 'Test health'
      responses:
        200:
          description: OK
      x-amazon-apigateway-integration:
        type: http
        httpMethod: GET
        uri: http://api-devl.give-and-take.tk:8080/ip
        responses:
          default:
            statusCode: '200'
